
GO
--Lasangna
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (80, 45)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (80, 46)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (81, 47)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (81, 48)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (82, 49)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (82, 50)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (83, 51)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (83, 52)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (84, 53)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (84, 54)


--Beverages
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (72, 10061)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (67, 10062)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (66, 10063)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (69, 10064)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (73, 10065)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (71, 10066)
--INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (, 10067)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (68, 10068)


--Pasta
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (76, 36)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (76, 37)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (77, 38)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (77, 39)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (78, 40)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (78, 41)
--INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (79, )

--Topping
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (85, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (86, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (87, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (88, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (89, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (90, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (92, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (93, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (94, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (95, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (96, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (97, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (98, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (99, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (100, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (101, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (102, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (103, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (104, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (105, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (106, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (107, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (108, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (109, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (110, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (111, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (112, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (113, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (114, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (115, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (116, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (117, 10070)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (119, 10070)

INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (85, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (86, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (87, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (88, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (89, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (90, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (92, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (93, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (94, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (95, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (96, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (97, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (98, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (99, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (100, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (101, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (102, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (103, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (104, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (105, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (106, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (107, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (108, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (109, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (110, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (111, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (112, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (113, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (114, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (115, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (116, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (117, 10071)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (119, 10071)

INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (85, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (86, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (87, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (88, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (89, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (90, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (92, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (93, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (94, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (95, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (96, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (97, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (98, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (99, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (100, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (101, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (102, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (103, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (104, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (105, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (106, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (107, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (108, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (109, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (110, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (111, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (112, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (113, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (114, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (115, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (116, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (117, 10072)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (119, 10072)

-- Salad
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (43, 10058)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (44, 10059)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (45, 10060)

-- Toast
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (46, 10055)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (47, 10056)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (48, 10057)

-- Wings
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (49, 55)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (50, 55)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (51, 55)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (52, 55)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (53, 56)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (54, 56)

-- Dip
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (55, 57)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (56, 57)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (57, 57)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (58, 57)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (59, 57)
INSERT INTO [dbo].[MenuItems] ([ItemId],[SpecialityPriceId]) VALUES (60, 57)

GO
